name: Build and Release

on:
  push:
    tags:
      - "v*.*.*" # This triggers the workflow on version tags like v1.0.0
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ["1.20.x"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Determine OS
        id: os-info
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "GOOS=linux" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "GOOS=windows" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "GOOS=darwin" >> $GITHUB_ENV
          fi
          echo "GOARCH=amd64" >> $GITHUB_ENV

      - name: Build for ${{ matrix.os }}
        run: |
          mkdir -p dist
          go build -o dist/task-cli-${GOOS}-${GOARCH}

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: task-cli-${{ matrix.os }}-${{ matrix.go-version }}
          path: dist/task-cli-${GOOS}-${GOARCH}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: task-cli-${{ matrix.os }}-${{ matrix.go-version }}
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
